<tr>
	<td>###:###mod_name###:###</td>
	<td>###:###ects###:###</td>
	<td>###:###try###:###</td>
	<td>###:###action_movedown###:###</td>
	<td>###:###action_moveup###:###</td>
	<td>###:###mark_plan###:###</td>
	<td>###:###mark_real###:###</td>
</tr>